"""Prepare the FORT-Cuh Roboflow COCO archive for one-class YOLO training.

The source archive combines several incompatible annotation vocabularies. This
converter deliberately produces one "player" class, drops part/identity labels,
clips boxes to image bounds, and never calls ZipFile.extractall. Output is
written through a temporary sibling directory and renamed into place only after
the complete dataset has been validated and copied.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass, field
from hashlib import sha256
import json
import math
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import tempfile
from typing import Any
import zipfile


EXPECTED_ARCHIVE_SHA256 = "eb0ea27ecbf7ac14e13485b6c8943a5bcacbb6adabc7d63d571ce3cb9af850b5"
SPLITS = ("train", "valid", "test")
ANNOTATION_FILENAME = "_annotations.coco.json"
IMAGE_SUFFIXES = frozenset({".jpg", ".jpeg", ".png"})
OUTPUT_CLASS_NAME = "player"
INCLUDED_CATEGORY_NAMES = frozenset(
    {"0", "fortnite", "player", "bots", "enemy", "hello", "people", "person"}
)
EXCLUDED_CATEGORY_NAMES = frozenset({"head", "body", "ally", "yourself"})
KNOWN_CATEGORY_NAMES = INCLUDED_CATEGORY_NAMES | EXCLUDED_CATEGORY_NAMES
REFERENCE_IMAGE_SIZE = 320
TINY_BOX_PIXELS = 2.0
MAX_ARCHIVE_UNCOMPRESSED_BYTES = 10 * 1024**3
MAX_ANNOTATION_BYTES = 100 * 1024**2
MAX_IMAGE_BYTES = 128 * 1024**2
COPY_CHUNK_BYTES = 1024 * 1024
ORIGINAL_BASENAME_PATTERN = re.compile(
    r"\.rf\.[^.]+(?=\.[^.]+$)",
    flags=re.IGNORECASE,
)
VIDEO_FRAME_PATTERN = re.compile(
    r"^(?P<source>.+_mp4)-[0-9]+_jpg(?=\.[^.]+$)",
    flags=re.IGNORECASE,
)
SOURCE_GROUPING_HEURISTIC_VERSION = 1

ATTRIBUTION_TEXT = """# FORT-Cuh dataset attribution

This prepared dataset is derived from **FORT-Cuh v1**, exported from Roboflow
Universe on August 9, 2026 and provided by Roboflow user Aviles Joseph:

https://universe.roboflow.com/aviles-joseph/fort-cuh-mji4f

The source dataset identifies its license as **CC BY 4.0**:

https://creativecommons.org/licenses/by/4.0/

Preparation changes made by ProAim:

- remapped the source labels "0", "Fortnite", "Player"/"player", "bots",
  "enemy", "hello", "people", and "person" to one class named "player";
- excluded "head", "body", "ally", and "Yourself" annotations;
- excluded images with no retained full-player box;
- clipped retained bounding boxes to their image bounds;
- copied image bytes without visual modification; and
- retained the supplied split assignments while recording conservative
  cross-split original-file and `*_mp4-<frame>_jpg` video-sequence overlap.

The source archive hash and exact conversion counts are recorded in
manifest.json. Retain this notice when sharing the prepared data or a model
derived from it. The supplied validation/test splits are not independent of the
training sources, so their metrics may be optimistic. This notice describes the
dataset's stated license; it is not legal advice and does not replace review of
third-party model licenses.
"""

DATASET_YAML = """# Generated by scripts/prepare_fort_cuh.py
train: images/train
val: images/valid
test: images/test
names:
  0: player
"""


class DatasetPreparationError(ValueError):
    """Raised when an input archive cannot be converted safely and unambiguously."""


@dataclass(slots=True)
class SplitReport:
    source_images: int = 0
    source_annotations: int = 0
    retained_images: int = 0
    retained_boxes: int = 0
    clipped_boxes: int = 0
    invalid_boxes_skipped: int = 0
    crowd_boxes_skipped: int = 0
    duplicate_boxes_skipped: int = 0
    tiny_boxes_at_320: int = 0
    excluded_images: int = 0
    unreferenced_archive_images: int = 0
    retained_source_categories: Counter[str] = field(default_factory=Counter)
    excluded_annotations: Counter[str] = field(default_factory=Counter)

    def serializable(self) -> dict[str, Any]:
        values = asdict(self)
        values["retained_source_categories"] = dict(
            sorted(self.retained_source_categories.items())
        )
        values["excluded_annotations"] = dict(sorted(self.excluded_annotations.items()))
        return values


@dataclass(frozen=True, slots=True)
class PreparedImage:
    split: str
    archive_name: str
    file_name: str
    label_lines: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class PreparationResult:
    output: Path
    archive_sha256: str
    reports: Mapping[str, SplitReport]
    leakage: Mapping[str, Any]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Convert the FORT-Cuh COCO zip into a deterministic one-class YOLO "
            "dataset without extracting unsafe archive paths."
        )
    )
    parser.add_argument("archive", type=Path, help="Path to FORT-Cuh.v1i.coco.zip.")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("datasets/fort_cuh_player"),
        help="New dataset directory (default: datasets/fort_cuh_player).",
    )
    parser.add_argument(
        "--expected-sha256",
        default=EXPECTED_ARCHIVE_SHA256,
        metavar="HEX",
        help=(
            "Required source archive SHA-256. The default pins the attached v1 "
            "archive; pass the independently verified hash for another copy/version."
        ),
    )
    return parser


def _sha256_file(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(COPY_CHUNK_BYTES), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _validate_expected_hash(value: str | None) -> str | None:
    if value is None:
        return None
    normalized = value.strip().lower()
    if not re.fullmatch(r"[0-9a-f]{64}", normalized):
        raise DatasetPreparationError("expected SHA-256 must contain exactly 64 hex digits")
    return normalized


def _safe_archive_name(name: str) -> PurePosixPath:
    if not isinstance(name, str) or not name or "\\" in name or "\x00" in name:
        raise DatasetPreparationError(f"unsafe zip member name: {name!r}")
    raw_parts = name.split("/")
    if any(part in {"", ".", ".."} for part in raw_parts):
        raise DatasetPreparationError(f"unsafe zip member path: {name!r}")
    path = PurePosixPath(name)
    if path.is_absolute():
        raise DatasetPreparationError(f"unsafe zip member path: {name!r}")
    if path.parts and re.fullmatch(r"[a-zA-Z]:", path.parts[0]):
        raise DatasetPreparationError(f"unsafe drive-qualified zip member: {name!r}")
    return path


def _safe_image_file_name(value: Any) -> str:
    if not isinstance(value, str) or not value or len(value) > 240:
        raise DatasetPreparationError(f"invalid COCO image file_name: {value!r}")
    if any(ord(character) < 32 for character in value):
        raise DatasetPreparationError(f"control character in COCO image file_name: {value!r}")
    path = _safe_archive_name(value)
    if len(path.parts) != 1 or path.name != value:
        raise DatasetPreparationError(
            f"COCO image file_name must be a plain filename, got {value!r}"
        )
    if path.suffix.casefold() not in IMAGE_SUFFIXES:
        raise DatasetPreparationError(f"unsupported image extension in {value!r}")
    return value


def _archive_index(archive: zipfile.ZipFile) -> dict[str, zipfile.ZipInfo]:
    index: dict[str, zipfile.ZipInfo] = {}
    total_uncompressed = 0
    for info in archive.infolist():
        name_for_validation = info.filename[:-1] if info.filename.endswith("/") else info.filename
        _safe_archive_name(name_for_validation)
        if info.filename in index:
            raise DatasetPreparationError(f"duplicate zip member name: {info.filename!r}")
        index[info.filename] = info
        if not info.is_dir():
            if info.file_size < 0:
                raise DatasetPreparationError(
                    f"zip member has an invalid declared size: {info.filename!r}"
                )
            total_uncompressed += info.file_size
            if total_uncompressed > MAX_ARCHIVE_UNCOMPRESSED_BYTES:
                raise DatasetPreparationError(
                    "archive declares more than 10 GiB of uncompressed data"
                )
    return index


def _read_member(
    archive: zipfile.ZipFile,
    info: zipfile.ZipInfo,
    *,
    maximum_bytes: int,
) -> bytes:
    if info.is_dir() or info.file_size > maximum_bytes:
        raise DatasetPreparationError(
            f"archive member is not a suitably sized file: {info.filename!r}"
        )
    with archive.open(info, "r") as source:
        data = source.read(maximum_bytes + 1)
    if len(data) > maximum_bytes or len(data) != info.file_size:
        raise DatasetPreparationError(
            f"archive member size mismatch or limit exceeded: {info.filename!r}"
        )
    return data


def _load_coco_json(
    archive: zipfile.ZipFile,
    index: Mapping[str, zipfile.ZipInfo],
    split: str,
) -> dict[str, Any]:
    member_name = f"{split}/{ANNOTATION_FILENAME}"
    info = index.get(member_name)
    if info is None:
        raise DatasetPreparationError(f"missing COCO annotations: {member_name}")
    raw = _read_member(archive, info, maximum_bytes=MAX_ANNOTATION_BYTES)
    try:
        value = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise DatasetPreparationError(f"invalid JSON in {member_name}: {exc}") from exc
    if not isinstance(value, dict):
        raise DatasetPreparationError(f"COCO root must be an object in {member_name}")
    for key in ("images", "annotations", "categories"):
        if not isinstance(value.get(key), list):
            raise DatasetPreparationError(f"COCO {key!r} must be a list in {member_name}")
    return value


def _integer_id(value: Any, description: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise DatasetPreparationError(f"{description} must be an integer, got {value!r}")
    return value


def _positive_dimension(value: Any, description: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise DatasetPreparationError(f"{description} must be numeric, got {value!r}")
    result = float(value)
    if not math.isfinite(result) or result <= 0.0:
        raise DatasetPreparationError(f"{description} must be finite and positive")
    return result


def _category_names(categories: Sequence[Any], split: str) -> dict[int, str]:
    result: dict[int, str] = {}
    unknown: set[str] = set()
    for entry in categories:
        if not isinstance(entry, dict):
            raise DatasetPreparationError(f"category entry must be an object in {split}")
        category_id = _integer_id(entry.get("id"), f"category id in {split}")
        name = entry.get("name")
        if not isinstance(name, str) or not name.strip():
            raise DatasetPreparationError(f"category {category_id} has no valid name in {split}")
        normalized = name.strip().casefold()
        if normalized not in KNOWN_CATEGORY_NAMES:
            unknown.add(name.strip())
        if category_id in result:
            raise DatasetPreparationError(f"duplicate category id {category_id} in {split}")
        result[category_id] = normalized
    if unknown:
        raise DatasetPreparationError(
            f"unknown categories in {split}: {', '.join(sorted(unknown, key=str.casefold))}. "
            "Update the explicit class map only after reviewing their boxes."
        )
    return result


def _images_by_id(images: Sequence[Any], split: str) -> dict[int, dict[str, Any]]:
    result: dict[int, dict[str, Any]] = {}
    names: set[str] = set()
    stems: set[str] = set()
    for entry in images:
        if not isinstance(entry, dict):
            raise DatasetPreparationError(f"image entry must be an object in {split}")
        image_id = _integer_id(entry.get("id"), f"image id in {split}")
        file_name = _safe_image_file_name(entry.get("file_name"))
        width = _positive_dimension(entry.get("width"), f"width for {file_name}")
        height = _positive_dimension(entry.get("height"), f"height for {file_name}")
        if image_id in result:
            raise DatasetPreparationError(f"duplicate image id {image_id} in {split}")
        if file_name in names:
            raise DatasetPreparationError(f"duplicate image filename {file_name!r} in {split}")
        stem_key = PurePosixPath(file_name).stem.casefold()
        if stem_key in stems:
            raise DatasetPreparationError(
                f"image filenames would collide as YOLO labels in {split}: {file_name!r}"
            )
        names.add(file_name)
        stems.add(stem_key)
        result[image_id] = {
            "id": image_id,
            "file_name": file_name,
            "width": width,
            "height": height,
        }
    return result


def _clip_and_normalize_box(
    bbox: Any,
    *,
    image_width: float,
    image_height: float,
) -> tuple[tuple[float, float, float, float] | None, bool]:
    if not isinstance(bbox, list) or len(bbox) != 4:
        raise DatasetPreparationError(f"COCO bbox must be a four-value list, got {bbox!r}")
    if any(isinstance(value, bool) or not isinstance(value, (int, float)) for value in bbox):
        raise DatasetPreparationError(f"COCO bbox values must be numeric, got {bbox!r}")
    x, y, width, height = (float(value) for value in bbox)
    if not all(math.isfinite(value) for value in (x, y, width, height)):
        raise DatasetPreparationError(f"COCO bbox values must be finite, got {bbox!r}")

    original = (x, y, x + width, y + height)
    x1 = min(image_width, max(0.0, original[0]))
    y1 = min(image_height, max(0.0, original[1]))
    x2 = min(image_width, max(0.0, original[2]))
    y2 = min(image_height, max(0.0, original[3]))
    clipped = (x1, y1, x2, y2) != original
    if x2 <= x1 or y2 <= y1:
        return None, clipped

    normalized_width = (x2 - x1) / image_width
    normalized_height = (y2 - y1) / image_height
    normalized_x = ((x1 + x2) * 0.5) / image_width
    normalized_y = ((y1 + y2) * 0.5) / image_height
    return (normalized_x, normalized_y, normalized_width, normalized_height), clipped


def _format_label(box: Sequence[float]) -> str:
    return "0 " + " ".join(f"{value:.10g}" for value in box)


def _prepare_split(
    archive: zipfile.ZipFile,
    index: Mapping[str, zipfile.ZipInfo],
    split: str,
) -> tuple[list[PreparedImage], SplitReport]:
    coco = _load_coco_json(archive, index, split)
    categories = _category_names(coco["categories"], split)
    images = _images_by_id(coco["images"], split)
    report = SplitReport(
        source_images=len(images),
        source_annotations=len(coco["annotations"]),
    )
    annotations_by_image: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for annotation in coco["annotations"]:
        if not isinstance(annotation, dict):
            raise DatasetPreparationError(f"annotation entry must be an object in {split}")
        image_id = _integer_id(annotation.get("image_id"), f"annotation image_id in {split}")
        category_id = _integer_id(
            annotation.get("category_id"), f"annotation category_id in {split}"
        )
        if image_id not in images:
            raise DatasetPreparationError(
                f"annotation references missing image id {image_id} in {split}"
            )
        if category_id not in categories:
            raise DatasetPreparationError(
                f"annotation references missing category id {category_id} in {split}"
            )
        annotations_by_image[image_id].append(annotation)

    referenced_image_members = {
        f"{split}/{image['file_name']}" for image in images.values()
    }
    archive_image_members = {
        name
        for name, info in index.items()
        if not info.is_dir()
        and PurePosixPath(name).parent == PurePosixPath(split)
        and PurePosixPath(name).suffix.casefold() in IMAGE_SUFFIXES
    }
    missing = sorted(referenced_image_members - archive_image_members)
    if missing:
        raise DatasetPreparationError(
            f"{split} references missing archive image(s): {', '.join(missing[:3])}"
        )
    report.unreferenced_archive_images = len(archive_image_members - referenced_image_members)

    prepared: list[PreparedImage] = []
    for image in sorted(images.values(), key=lambda value: value["file_name"].casefold()):
        lines: list[str] = []
        seen_lines: set[str] = set()
        annotations = sorted(
            annotations_by_image.get(image["id"], ()),
            key=lambda value: (
                int(value.get("id", 0)) if isinstance(value.get("id"), int) else 0,
                int(value["category_id"]),
                tuple(str(part) for part in value.get("bbox", ())),
            ),
        )
        for annotation in annotations:
            source_category = categories[int(annotation["category_id"])]
            if source_category in EXCLUDED_CATEGORY_NAMES:
                report.excluded_annotations[source_category] += 1
                continue
            if bool(annotation.get("iscrowd", False)):
                report.crowd_boxes_skipped += 1
                continue
            normalized, was_clipped = _clip_and_normalize_box(
                annotation.get("bbox"),
                image_width=float(image["width"]),
                image_height=float(image["height"]),
            )
            if was_clipped:
                report.clipped_boxes += 1
            if normalized is None:
                report.invalid_boxes_skipped += 1
                continue
            if (
                normalized[2] * REFERENCE_IMAGE_SIZE < TINY_BOX_PIXELS
                or normalized[3] * REFERENCE_IMAGE_SIZE < TINY_BOX_PIXELS
            ):
                report.tiny_boxes_at_320 += 1
            line = _format_label(normalized)
            if line in seen_lines:
                report.duplicate_boxes_skipped += 1
                continue
            seen_lines.add(line)
            lines.append(line)
            report.retained_boxes += 1
            report.retained_source_categories[source_category] += 1

        if not lines:
            continue
        file_name = str(image["file_name"])
        prepared.append(
            PreparedImage(
                split=split,
                archive_name=f"{split}/{file_name}",
                file_name=file_name,
                label_lines=tuple(lines),
            )
        )

    report.retained_images = len(prepared)
    report.excluded_images = report.source_images - report.retained_images
    if not prepared or report.retained_boxes <= 0:
        raise DatasetPreparationError(f"no usable player annotations remained in {split}")
    return prepared, report


def _original_basename(file_name: str) -> str:
    return ORIGINAL_BASENAME_PATTERN.sub("", file_name).casefold()


def _video_sequence_name(file_name: str) -> str | None:
    """Return a conservative source-video key for Roboflow-exported frame names."""

    original = _original_basename(file_name)
    match = VIDEO_FRAME_PATTERN.match(original)
    return match.group("source").casefold() if match is not None else None


def _source_group_key(file_name: str) -> str:
    """Group only exact original names or explicit ``_mp4-N_jpg`` frame sequences."""

    video_sequence = _video_sequence_name(file_name)
    if video_sequence is not None:
        return f"video_sequence:{video_sequence}"
    return f"original_file:{_original_basename(file_name)}"


def _copy_image_member(
    archive: zipfile.ZipFile,
    info: zipfile.ZipInfo,
    destination: Path,
) -> str:
    if info.is_dir() or info.file_size > MAX_IMAGE_BYTES:
        raise DatasetPreparationError(
            f"image member is not a suitably sized file: {info.filename!r}"
        )
    digest = sha256()
    copied = 0
    with archive.open(info, "r") as source, destination.open("xb") as target:
        while True:
            chunk = source.read(COPY_CHUNK_BYTES)
            if not chunk:
                break
            copied += len(chunk)
            if copied > MAX_IMAGE_BYTES or copied > info.file_size:
                raise DatasetPreparationError(
                    f"image member exceeds its safe size: {info.filename!r}"
                )
            digest.update(chunk)
            target.write(chunk)
    if copied != info.file_size:
        raise DatasetPreparationError(f"image member size mismatch: {info.filename!r}")
    return digest.hexdigest()


def _cross_split_groups(
    values: Mapping[str, Sequence[tuple[str, str]]],
) -> list[dict[str, Any]]:
    groups: list[dict[str, Any]] = []
    for key, entries in sorted(values.items()):
        if len({split for split, _name in entries}) <= 1:
            continue
        groups.append(
            {
                "key": key,
                "files": [f"{split}/{name}" for split, name in sorted(entries)],
            }
        )
    return groups


def _grouped_file_count(groups: Sequence[Mapping[str, Any]]) -> int:
    return sum(len(group["files"]) for group in groups)


def _write_prepared_dataset(
    archive: zipfile.ZipFile,
    index: Mapping[str, zipfile.ZipInfo],
    prepared_by_split: Mapping[str, Sequence[PreparedImage]],
    reports: Mapping[str, SplitReport],
    archive_digest: str,
    output: Path,
) -> Mapping[str, Any]:
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(
        tempfile.mkdtemp(prefix=f".{output.name}.preparing-", dir=str(output.parent))
    )
    try:
        originals: dict[str, list[tuple[str, str]]] = defaultdict(list)
        digests: dict[str, list[tuple[str, str]]] = defaultdict(list)
        source_groups: dict[str, list[tuple[str, str]]] = defaultdict(list)
        video_sequences: dict[str, list[tuple[str, str]]] = defaultdict(list)
        for split in SPLITS:
            image_dir = temporary / "images" / split
            label_dir = temporary / "labels" / split
            image_dir.mkdir(parents=True)
            label_dir.mkdir(parents=True)
            for prepared in prepared_by_split[split]:
                destination = image_dir / prepared.file_name
                digest = _copy_image_member(
                    archive,
                    index[prepared.archive_name],
                    destination,
                )
                label_path = label_dir / f"{PurePosixPath(prepared.file_name).stem}.txt"
                label_path.write_text("\n".join(prepared.label_lines) + "\n", encoding="utf-8")
                originals[_original_basename(prepared.file_name)].append(
                    (split, prepared.file_name)
                )
                digests[digest].append((split, prepared.file_name))
                source_groups[_source_group_key(prepared.file_name)].append(
                    (split, prepared.file_name)
                )
                video_sequence = _video_sequence_name(prepared.file_name)
                if video_sequence is not None:
                    video_sequences[video_sequence].append((split, prepared.file_name))

        basename_groups = _cross_split_groups(originals)
        digest_groups = _cross_split_groups(digests)
        source_group_overlaps = _cross_split_groups(source_groups)
        video_sequence_overlaps = _cross_split_groups(video_sequences)
        leakage: dict[str, Any] = {
            "source_grouping_heuristic": {
                "version": SOURCE_GROUPING_HEURISTIC_VERSION,
                "roboflow_suffix_regex": ORIGINAL_BASENAME_PATTERN.pattern,
                "video_frame_regex": VIDEO_FRAME_PATTERN.pattern,
                "description": (
                    "Strip one Roboflow .rf.<hash> suffix. Group explicit "
                    "*_mp4-<digits>_jpg frame names by the prefix ending in _mp4; "
                    "group every other image only by its complete stripped original "
                    "filename. No visual-similarity or timestamp guessing is used."
                ),
            },
            "cross_split_original_basename_groups": len(basename_groups),
            "cross_split_original_basenames": basename_groups,
            "cross_split_exact_duplicate_groups": len(digest_groups),
            "cross_split_exact_duplicates": digest_groups,
            "cross_split_source_groups": len(source_group_overlaps),
            "cross_split_source_group_images": _grouped_file_count(
                source_group_overlaps
            ),
            "cross_split_source_group_details": source_group_overlaps,
            "cross_split_video_sequence_groups": len(video_sequence_overlaps),
            "cross_split_video_sequence_images": _grouped_file_count(
                video_sequence_overlaps
            ),
            "cross_split_video_sequence_details": video_sequence_overlaps,
        }
        manifest = {
            "schema_version": 1,
            "source": {
                "dataset": "FORT-Cuh v1",
                "url": "https://universe.roboflow.com/aviles-joseph/fort-cuh-mji4f",
                "license": "CC BY 4.0",
                "archive_sha256": archive_digest,
            },
            "conversion": {
                "output_class_names": [OUTPUT_CLASS_NAME],
                "included_source_categories_casefolded": sorted(INCLUDED_CATEGORY_NAMES),
                "excluded_source_categories_casefolded": sorted(EXCLUDED_CATEGORY_NAMES),
                "images_without_a_retained_box_are_excluded": True,
                "boxes_are_clipped_to_image_bounds": True,
                "reference_inference_size": REFERENCE_IMAGE_SIZE,
            },
            "splits": {split: reports[split].serializable() for split in SPLITS},
            "leakage": leakage,
        }
        (temporary / "fort_cuh_player.yaml").write_text(DATASET_YAML, encoding="utf-8")
        (temporary / "labels.txt").write_text(f"{OUTPUT_CLASS_NAME}\n", encoding="utf-8")
        (temporary / "ATTRIBUTION.md").write_text(ATTRIBUTION_TEXT, encoding="utf-8")
        (temporary / "manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        temporary.rename(output)
        return leakage
    except Exception:
        shutil.rmtree(temporary, ignore_errors=True)
        raise


def prepare_dataset(
    archive_path: str | Path,
    output_path: str | Path,
    *,
    expected_sha256: str | None = EXPECTED_ARCHIVE_SHA256,
) -> PreparationResult:
    """Validate and convert one archive, refusing to replace an existing output."""

    archive_file = Path(archive_path).expanduser().resolve()
    output = Path(output_path).expanduser().resolve()
    if not archive_file.is_file():
        raise DatasetPreparationError(f"archive not found: {archive_file}")
    if archive_file.suffix.casefold() != ".zip":
        raise DatasetPreparationError(f"source archive must be a .zip file: {archive_file}")
    if output.exists() or output.is_symlink() or os.path.lexists(output):
        raise DatasetPreparationError(f"output already exists; refusing to replace it: {output}")

    expected = _validate_expected_hash(expected_sha256)
    archive_digest = _sha256_file(archive_file)
    if expected is not None and archive_digest != expected:
        raise DatasetPreparationError(
            f"archive SHA-256 mismatch: expected {expected}, got {archive_digest}"
        )

    try:
        with zipfile.ZipFile(archive_file, "r") as archive:
            index = _archive_index(archive)
            prepared_by_split: dict[str, list[PreparedImage]] = {}
            reports: dict[str, SplitReport] = {}
            for split in SPLITS:
                prepared, report = _prepare_split(archive, index, split)
                prepared_by_split[split] = prepared
                reports[split] = report
            leakage = _write_prepared_dataset(
                archive,
                index,
                prepared_by_split,
                reports,
                archive_digest,
                output,
            )
    except zipfile.BadZipFile as exc:
        raise DatasetPreparationError(f"invalid zip archive: {archive_file}") from exc

    return PreparationResult(
        output=output,
        archive_sha256=archive_digest,
        reports=reports,
        leakage=leakage,
    )


def _print_result(result: PreparationResult) -> None:
    print(f"Prepared one-class dataset: {result.output}")
    print(f"Source SHA-256: {result.archive_sha256}")
    for split in SPLITS:
        report = result.reports[split]
        print(
            f"{split}: {report.retained_images}/{report.source_images} images | "
            f"{report.retained_boxes} boxes | {report.clipped_boxes} clipped | "
            f"{report.invalid_boxes_skipped} invalid skipped | "
            f"{report.tiny_boxes_at_320} under 2 px at 320"
        )
    print(
        "Cross-split leakage warning: "
        f"{result.leakage['cross_split_original_basename_groups']} repeated original "
        "basename group(s), "
        f"{result.leakage['cross_split_exact_duplicate_groups']} exact-byte group(s), "
        f"and {result.leakage['cross_split_source_groups']} conservative source "
        f"group(s) spanning {result.leakage['cross_split_source_group_images']} image(s) "
        f"({result.leakage['cross_split_video_sequence_groups']} explicit video sequence(s))."
    )
    print(
        "The supplied validation/test splits are not independent of training; "
        "their metrics may be optimistic."
    )
    print(f"Training YAML: {result.output / 'fort_cuh_player.yaml'}")
    print(f"Runtime labels: {result.output / 'labels.txt'}")


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        result = prepare_dataset(
            args.archive,
            args.output,
            expected_sha256=args.expected_sha256,
        )
    except DatasetPreparationError as exc:
        parser.error(str(exc))
    _print_result(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
